import { BcrFormConfig } from './types';

export const bcrFormConfig: BcrFormConfig = {
  id: 'bcr-form',
  title: 'Beneficiary Change Request',
  subtitle: 'Sun Life Financial Plans, Inc.',
  pdfTemplateUrl: '/forms/SLFPI_Beneficiary Change Request.pdf',
  pageWidth: 612,
  pageHeight: 792,
  totalPages: 4,

  sections: [
    {
      key: 'section_a',
      letter: 'A',
      title: 'General Information',
      fieldKeys: [
        'planholder_type_individual',
        'planholder_type_company',
        'plan_numbers',
        'planholder_last_name',
        'planholder_first_name',
        'planholder_mi',
        'company_name',
      ],
    },
    {
      key: 'section_b',
      letter: 'B',
      title: 'Change Request Type',
      fieldKeys: [
        'change_type_add',
        'change_type_remove',
        'change_type_change',
      ],
    },
    {
      key: 'section_b1',
      letter: 'B.1',
      title: 'Add Beneficiary 1',
      fieldKeys: [
        'beneficiary1_name',
        'beneficiary1_birthdate',
        'beneficiary1_country_birth',
        'beneficiary1_citizenships',
        'beneficiary1_relationship_father',
        'beneficiary1_relationship_mother',
        'beneficiary1_relationship_employer',
        'beneficiary1_relationship_others_check',
        'beneficiary1_relationship_others',
        'beneficiary1_type_primary',
        'beneficiary1_type_contingent',
        'beneficiary1_designation_revocable',
        'beneficiary1_designation_irrevocable',
        'beneficiary1_phone',
        'beneficiary1_address',
      ],
    },
    {
      key: 'section_b2',
      letter: 'B.2',
      title: 'Add Beneficiary 2',
      fieldKeys: [
        'beneficiary2_name',
        'beneficiary2_birthdate',
        'beneficiary2_country_birth',
        'beneficiary2_citizenships',
        'beneficiary2_relationship_father',
        'beneficiary2_relationship_mother',
        'beneficiary2_relationship_employer',
        'beneficiary2_relationship_others_check',
        'beneficiary2_relationship_others',
        'beneficiary2_type_primary',
        'beneficiary2_type_contingent',
        'beneficiary2_designation_revocable',
        'beneficiary2_designation_irrevocable',
        'beneficiary2_phone',
        'beneficiary2_address',
      ],
    },
    {
      key: 'section_b3',
      letter: 'B.3',
      title: 'Remove Beneficiary',
      fieldKeys: [
        'remove_beneficiary1_name',
        'remove_beneficiary2_name',
      ],
    },
    {
      key: 'section_b4',
      letter: 'B.4',
      title: 'Change Information',
      fieldKeys: [
        'change_original_name',
        'change_new_name',
        'change_birthdate',
        'change_phone',
        'change_address',
      ],
    },
    {
      key: 'section_c',
      letter: 'C',
      title: 'Tax Compliance',
      fieldKeys: [
        'compliance_type_resident',
        'compliance_resident_country',
        'compliance_type_citizen',
        'compliance_citizen_country',
        'compliance_type_none',
      ],
    },
    {
      key: 'section_d',
      letter: 'D',
      title: 'Signatures & Acknowledgments',
      fieldKeys: [
        'place_of_signing',
        'date_of_signing',
        'planholder_printed_name',
        'planholder_signature',
        'witness_name',
        'witness_signature',
        'irrevocable_ben1_name',
        'irrevocable_ben1_signature',
        'witness2_name',
        'witness2_signature',
        'wants_communication_yes',
        'wants_communication_no',
      ],
    },
    {
      key: 'section_e',
      letter: 'E',
      title: 'Company Use Only',
      fieldKeys: ['company_use_only_notes'],
    },
  ],

  fields: [
    // ════════════════════════════════════════════════════════════════════════
    // PAGE 1
    // ════════════════════════════════════════════════════════════════════════
    {
      key: 'plan_numbers',
      label: 'Policy / Plan Number(s)',
      type: 'text',
      page: 1,
      x: 430,
      y: 735,
      width: 150,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_a',
      placeholder: 'Enter Policy #',
      required: true,
    },
    {
      key: 'planholder_type_individual',
      label: 'Individual Planholder',
      type: 'radio',
      page: 1,
      x: 40,
      y: 690,
      width: 16,
      height: 16,
      radioValue: 'individual',
      sectionKey: 'section_a',
    },
    {
      key: 'planholder_type_company',
      label: 'Company / Business Planholder',
      type: 'radio',
      page: 1,
      x: 180,
      y: 690,
      width: 16,
      height: 16,
      radioValue: 'company',
      sectionKey: 'section_a',
    },
    {
      key: 'planholder_last_name',
      label: 'Planholder Last Name',
      type: 'text',
      page: 1,
      x: 40,
      y: 660,
      width: 160,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_a',
      placeholder: 'Last Name',
      required: true,
    },
    {
      key: 'planholder_first_name',
      label: 'Planholder First Name',
      type: 'text',
      page: 1,
      x: 210,
      y: 660,
      width: 160,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_a',
      placeholder: 'First Name',
      required: true,
    },
    {
      key: 'planholder_mi',
      label: 'Middle Name / Initial',
      type: 'text',
      page: 1,
      x: 380,
      y: 660,
      width: 80,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_a',
      placeholder: 'MI',
    },
    {
      key: 'company_name',
      label: 'Company / Business Name',
      type: 'text',
      page: 1,
      x: 40,
      y: 625,
      width: 520,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_a',
      placeholder: 'Company Name',
    },

    // B: Change Type Checkboxes
    {
      key: 'change_type_add',
      label: 'Add Beneficiary(ies)',
      type: 'radio',
      page: 1,
      x: 40,
      y: 580,
      width: 16,
      height: 16,
      radioValue: 'add',
      sectionKey: 'section_b',
    },
    {
      key: 'change_type_remove',
      label: 'Remove Beneficiary(ies)',
      type: 'radio',
      page: 1,
      x: 180,
      y: 580,
      width: 16,
      height: 16,
      radioValue: 'remove',
      sectionKey: 'section_b',
    },
    {
      key: 'change_type_change',
      label: 'Change Beneficiary Information',
      type: 'radio',
      page: 1,
      x: 340,
      y: 580,
      width: 16,
      height: 16,
      radioValue: 'change',
      sectionKey: 'section_b',
    },

    // B.1: Beneficiary 1 (Page 1 bottom)
    {
      key: 'beneficiary1_name',
      label: 'Beneficiary 1 Full Name',
      type: 'text',
      page: 1,
      x: 40,
      y: 510,
      width: 520,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_b1',
      placeholder: 'Last Name, First Name Middle Name',
    },
    {
      key: 'beneficiary1_birthdate',
      label: 'Beneficiary 1 Birthdate',
      type: 'date',
      page: 1,
      x: 40,
      y: 475,
      width: 120,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_b1',
    },
    {
      key: 'beneficiary1_country_birth',
      label: 'Beneficiary 1 Country of Birth',
      type: 'text',
      page: 1,
      x: 180,
      y: 475,
      width: 180,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_b1',
      placeholder: 'Country of Birth',
    },
    {
      key: 'beneficiary1_citizenships',
      label: 'Beneficiary 1 Citizenship(s)',
      type: 'text',
      page: 1,
      x: 380,
      y: 475,
      width: 180,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_b1',
      placeholder: 'Citizenship / Nationality',
    },
    {
      key: 'beneficiary1_relationship_father',
      label: 'Relationship: Father',
      type: 'radio',
      page: 1,
      x: 40,
      y: 440,
      width: 14,
      height: 14,
      radioValue: 'Father',
      sectionKey: 'section_b1',
    },
    {
      key: 'beneficiary1_relationship_mother',
      label: 'Relationship: Mother',
      type: 'radio',
      page: 1,
      x: 100,
      y: 440,
      width: 14,
      height: 14,
      radioValue: 'Mother',
      sectionKey: 'section_b1',
    },
    {
      key: 'beneficiary1_relationship_employer',
      label: 'Relationship: Employer',
      type: 'radio',
      page: 1,
      x: 160,
      y: 440,
      width: 14,
      height: 14,
      radioValue: 'Employer',
      sectionKey: 'section_b1',
    },
    {
      key: 'beneficiary1_relationship_others_check',
      label: 'Relationship: Others',
      type: 'radio',
      page: 1,
      x: 230,
      y: 440,
      width: 14,
      height: 14,
      radioValue: 'Others',
      sectionKey: 'section_b1',
    },
    {
      key: 'beneficiary1_relationship_others',
      label: 'Relationship Details (Specify)',
      type: 'text',
      page: 1,
      x: 290,
      y: 440,
      width: 120,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_b1',
      placeholder: 'Specify relationship',
    },
    {
      key: 'beneficiary1_type_primary',
      label: 'Type: Primary',
      type: 'radio',
      page: 1,
      x: 420,
      y: 440,
      width: 14,
      height: 14,
      radioValue: 'Primary',
      sectionKey: 'section_b1',
    },
    {
      key: 'beneficiary1_type_contingent',
      label: 'Type: Contingent',
      type: 'radio',
      page: 1,
      x: 480,
      y: 440,
      width: 14,
      height: 14,
      radioValue: 'Contingent',
      sectionKey: 'section_b1',
    },
    {
      key: 'beneficiary1_designation_revocable',
      label: 'Designation: Revocable',
      type: 'radio',
      page: 1,
      x: 40,
      y: 420,
      width: 14,
      height: 14,
      radioValue: 'Revocable',
      sectionKey: 'section_b1',
    },
    {
      key: 'beneficiary1_designation_irrevocable',
      label: 'Designation: Irrevocable',
      type: 'radio',
      page: 1,
      x: 120,
      y: 420,
      width: 14,
      height: 14,
      radioValue: 'Irrevocable',
      sectionKey: 'section_b1',
    },
    {
      key: 'beneficiary1_phone',
      label: 'Beneficiary 1 Phone / Mobile',
      type: 'text',
      page: 1,
      x: 40,
      y: 395,
      width: 200,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_b1',
      placeholder: '+63 9XX XXX XXXX',
    },
    {
      key: 'beneficiary1_address',
      label: 'Beneficiary 1 Address',
      type: 'textarea',
      page: 1,
      x: 40,
      y: 355,
      width: 520,
      height: 35,
      fontSize: 8.5,
      sectionKey: 'section_b1',
      placeholder: 'Complete Residential Address',
    },

    // ════════════════════════════════════════════════════════════════════════
    // PAGE 2
    // ════════════════════════════════════════════════════════════════════════
    {
      key: 'beneficiary2_name',
      label: 'Beneficiary 2 Full Name',
      type: 'text',
      page: 2,
      x: 40,
      y: 700,
      width: 520,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_b2',
      placeholder: 'Last Name, First Name Middle Name',
    },
    {
      key: 'beneficiary2_birthdate',
      label: 'Beneficiary 2 Birthdate',
      type: 'date',
      page: 2,
      x: 40,
      y: 665,
      width: 120,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_b2',
    },
    {
      key: 'beneficiary2_country_birth',
      label: 'Beneficiary 2 Country of Birth',
      type: 'text',
      page: 2,
      x: 180,
      y: 665,
      width: 180,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_b2',
      placeholder: 'Country of Birth',
    },
    {
      key: 'beneficiary2_citizenships',
      label: 'Beneficiary 2 Citizenship(s)',
      type: 'text',
      page: 2,
      x: 380,
      y: 665,
      width: 180,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_b2',
      placeholder: 'Citizenship / Nationality',
    },
    {
      key: 'beneficiary2_relationship_father',
      label: 'Relationship: Father',
      type: 'radio',
      page: 2,
      x: 40,
      y: 630,
      width: 14,
      height: 14,
      radioValue: 'Father',
      sectionKey: 'section_b2',
    },
    {
      key: 'beneficiary2_relationship_mother',
      label: 'Relationship: Mother',
      type: 'radio',
      page: 2,
      x: 100,
      y: 630,
      width: 14,
      height: 14,
      radioValue: 'Mother',
      sectionKey: 'section_b2',
    },
    {
      key: 'beneficiary2_relationship_employer',
      label: 'Relationship: Employer',
      type: 'radio',
      page: 2,
      x: 160,
      y: 630,
      width: 14,
      height: 14,
      radioValue: 'Employer',
      sectionKey: 'section_b2',
    },
    {
      key: 'beneficiary2_relationship_others_check',
      label: 'Relationship: Others',
      type: 'radio',
      page: 2,
      x: 230,
      y: 630,
      width: 14,
      height: 14,
      radioValue: 'Others',
      sectionKey: 'section_b2',
    },
    {
      key: 'beneficiary2_relationship_others',
      label: 'Relationship Details (Specify)',
      type: 'text',
      page: 2,
      x: 290,
      y: 630,
      width: 120,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_b2',
      placeholder: 'Specify relationship',
    },
    {
      key: 'beneficiary2_type_primary',
      label: 'Type: Primary',
      type: 'radio',
      page: 2,
      x: 420,
      y: 630,
      width: 14,
      height: 14,
      radioValue: 'Primary',
      sectionKey: 'section_b2',
    },
    {
      key: 'beneficiary2_type_contingent',
      label: 'Type: Contingent',
      type: 'radio',
      page: 2,
      x: 480,
      y: 630,
      width: 14,
      height: 14,
      radioValue: 'Contingent',
      sectionKey: 'section_b2',
    },
    {
      key: 'beneficiary2_designation_revocable',
      label: 'Designation: Revocable',
      type: 'radio',
      page: 2,
      x: 40,
      y: 610,
      width: 14,
      height: 14,
      radioValue: 'Revocable',
      sectionKey: 'section_b2',
    },
    {
      key: 'beneficiary2_designation_irrevocable',
      label: 'Designation: Irrevocable',
      type: 'radio',
      page: 2,
      x: 120,
      y: 610,
      width: 14,
      height: 14,
      radioValue: 'Irrevocable',
      sectionKey: 'section_b2',
    },
    {
      key: 'beneficiary2_phone',
      label: 'Beneficiary 2 Phone',
      type: 'text',
      page: 2,
      x: 40,
      y: 585,
      width: 200,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_b2',
    },
    {
      key: 'beneficiary2_address',
      label: 'Beneficiary 2 Address',
      type: 'textarea',
      page: 2,
      x: 40,
      y: 545,
      width: 520,
      height: 35,
      fontSize: 8.5,
      sectionKey: 'section_b2',
    },

    // B.3: Remove Beneficiary
    {
      key: 'remove_beneficiary1_name',
      label: 'Remove Beneficiary 1 Name',
      type: 'text',
      page: 2,
      x: 40,
      y: 485,
      width: 520,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_b3',
      placeholder: 'Name of Beneficiary to Remove',
    },
    {
      key: 'remove_beneficiary2_name',
      label: 'Remove Beneficiary 2 Name',
      type: 'text',
      page: 2,
      x: 40,
      y: 455,
      width: 520,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_b3',
      placeholder: 'Name of Additional Beneficiary to Remove',
    },

    // B.4: Change Information
    {
      key: 'change_original_name',
      label: 'Original Beneficiary Name',
      type: 'text',
      page: 2,
      x: 40,
      y: 390,
      width: 520,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_b4',
      placeholder: 'Original Beneficiary Name as printed in plan',
    },
    {
      key: 'change_new_name',
      label: 'Updated / Corrected Name',
      type: 'text',
      page: 2,
      x: 40,
      y: 345,
      width: 520,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_b4',
      placeholder: 'New Corrected Name',
    },
    {
      key: 'change_birthdate',
      label: 'Corrected Birthdate',
      type: 'date',
      page: 2,
      x: 40,
      y: 310,
      width: 150,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_b4',
    },
    {
      key: 'change_phone',
      label: 'Corrected Phone',
      type: 'text',
      page: 2,
      x: 210,
      y: 310,
      width: 180,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_b4',
    },
    {
      key: 'change_address',
      label: 'Corrected Address',
      type: 'textarea',
      page: 2,
      x: 40,
      y: 260,
      width: 520,
      height: 35,
      fontSize: 8.5,
      sectionKey: 'section_b4',
    },

    // ════════════════════════════════════════════════════════════════════════
    // PAGE 3
    // ════════════════════════════════════════════════════════════════════════
    {
      key: 'compliance_type_resident',
      label: 'US Resident',
      type: 'radio',
      page: 3,
      x: 40,
      y: 690,
      width: 16,
      height: 16,
      radioValue: 'resident',
      sectionKey: 'section_c',
    },
    {
      key: 'compliance_resident_country',
      label: 'US Resident Country',
      type: 'text',
      page: 3,
      x: 220,
      y: 690,
      width: 250,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_c',
    },
    {
      key: 'compliance_type_citizen',
      label: 'US Citizen',
      type: 'radio',
      page: 3,
      x: 40,
      y: 660,
      width: 16,
      height: 16,
      radioValue: 'citizen',
      sectionKey: 'section_c',
    },
    {
      key: 'compliance_citizen_country',
      label: 'US Citizen Country',
      type: 'text',
      page: 3,
      x: 220,
      y: 660,
      width: 250,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_c',
    },
    {
      key: 'compliance_type_none',
      label: 'None of the above',
      type: 'radio',
      page: 3,
      x: 40,
      y: 630,
      width: 16,
      height: 16,
      radioValue: 'none',
      sectionKey: 'section_c',
    },

    // Section D: Signatures
    {
      key: 'place_of_signing',
      label: 'Place of Signing',
      type: 'text',
      page: 3,
      x: 40,
      y: 530,
      width: 320,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_d',
      placeholder: 'City / Municipality',
    },
    {
      key: 'date_of_signing',
      label: 'Date of Signing',
      type: 'date',
      page: 3,
      x: 380,
      y: 530,
      width: 180,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_d',
    },
    {
      key: 'planholder_printed_name',
      label: 'Printed Name of Planholder',
      type: 'text',
      page: 3,
      x: 40,
      y: 460,
      width: 250,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_d',
      required: true,
    },
    {
      key: 'planholder_signature',
      label: 'Planholder Signature',
      type: 'signature',
      page: 3,
      x: 40,
      y: 390,
      width: 250,
      height: 50,
      sectionKey: 'section_d',
      required: true,
    },
    {
      key: 'witness_name',
      label: 'Printed Name of Witness',
      type: 'text',
      page: 3,
      x: 310,
      y: 460,
      width: 250,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_d',
    },
    {
      key: 'witness_signature',
      label: 'Witness Signature',
      type: 'signature',
      page: 3,
      x: 310,
      y: 390,
      width: 250,
      height: 50,
      sectionKey: 'section_d',
    },

    // ════════════════════════════════════════════════════════════════════════
    // PAGE 4
    // ════════════════════════════════════════════════════════════════════════
    {
      key: 'irrevocable_ben1_name',
      label: 'Irrevocable Beneficiary Printed Name',
      type: 'text',
      page: 4,
      x: 40,
      y: 660,
      width: 250,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_d',
    },
    {
      key: 'irrevocable_ben1_signature',
      label: 'Irrevocable Beneficiary Signature',
      type: 'signature',
      page: 4,
      x: 40,
      y: 590,
      width: 250,
      height: 50,
      sectionKey: 'section_d',
    },
    {
      key: 'witness2_name',
      label: 'Additional Witness Printed Name',
      type: 'text',
      page: 4,
      x: 40,
      y: 520,
      width: 250,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_d',
    },
    {
      key: 'witness2_signature',
      label: 'Additional Witness Signature',
      type: 'signature',
      page: 4,
      x: 40,
      y: 450,
      width: 250,
      height: 50,
      sectionKey: 'section_d',
    },
    {
      key: 'wants_communication_yes',
      label: 'Receive Promotional Communications: Yes',
      type: 'radio',
      page: 4,
      x: 140,
      y: 350,
      width: 16,
      height: 16,
      radioValue: true,
      sectionKey: 'section_d',
    },
    {
      key: 'wants_communication_no',
      label: 'Receive Promotional Communications: No',
      type: 'radio',
      page: 4,
      x: 180,
      y: 350,
      width: 16,
      height: 16,
      radioValue: false,
      sectionKey: 'section_d',
    },

    // Section E: Company Use Only
    {
      key: 'company_use_only_notes',
      label: 'Company Use Notes / Processing Remarks',
      type: 'textarea',
      page: 4,
      x: 40,
      y: 220,
      width: 520,
      height: 80,
      fontSize: 8.5,
      sectionKey: 'section_e',
    },
  ],
};
