import { PdfFormConfig } from '@/app/components/pdf-engine/types';

export const acrFormConfig: PdfFormConfig = {
  id: 'acr-form',
  title: 'Advisor Change Request',
  subtitle: 'Sun Life of Canada (Philippines), Inc.',
  pdfTemplateUrl: '/forms/SLOCPI_Advisor_Change_Request.pdf',
  pageWidth: 612,
  pageHeight: 792,
  totalPages: 2,

  sections: [
    {
      key: 'section_a',
      letter: 'A',
      title: 'General Information',
      fieldKeys: [
        'client_last_name',
        'client_first_name',
        'client_middle_name',
        'client_dob',
        'company_name',
        'designation',
      ],
    },
    {
      key: 'section_b',
      letter: 'B',
      title: 'Request Details',
      fieldKeys: [
        'request_type_specific',
        'policy_numbers',
        'request_type_all',
        'account_individual_life',
        'account_group_life',
        'account_mutual_fund',
        'account_pre_need',
        'reference_policy_number',
      ],
    },
    {
      key: 'section_c',
      letter: 'C',
      title: 'Reason for Change',
      fieldKeys: [
        'reason_type_no_advisor',
        'reason_type_prefer_another',
        'reason_details',
      ],
    },
    {
      key: 'section_d',
      letter: 'D',
      title: 'New Advisor Information',
      fieldKeys: [
        'new_advisor_last_name',
        'new_advisor_first_name',
        'new_advisor_middle_name',
      ],
    },
    {
      key: 'section_e',
      letter: 'E',
      title: 'Signatures & Acknowledgments',
      fieldKeys: [
        'client_full_name_pg2',
        'place_of_signing',
        'date_of_signing',
        'policy_owner_signature',
        'new_advisor_signature',
        'code_number',
        'nbo_iso',
      ],
    },
    {
      key: 'section_f',
      letter: 'F',
      title: 'Communication Preference',
      fieldKeys: [
        'wants_communication_yes',
        'wants_communication_no',
      ],
    },
    {
      key: 'section_g',
      letter: 'G',
      title: 'For Office Use Only',
      fieldKeys: [
        'received_by_staff',
        'receiving_department',
        'date_received',
        'time_received',
      ],
    },
  ],

  fields: [
    // ════════════════════════════════════════════════════════════════════════
    // PAGE 1
    // ════════════════════════════════════════════════════════════════════════
    {
      key: 'client_last_name',
      label: 'Policy Owner Last Name',
      type: 'readonly',
      page: 1,
      x: 35,
      y: 518,
      width: 135,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_a',
      sectionTitle: 'A. General Information',
      description: 'Auto-populated from selected client record.',
    },
    {
      key: 'client_first_name',
      label: 'Policy Owner First Name',
      type: 'readonly',
      page: 1,
      x: 176,
      y: 518,
      width: 130,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_a',
      sectionTitle: 'A. General Information',
    },
    {
      key: 'client_middle_name',
      label: 'Policy Owner Middle Name',
      type: 'readonly',
      page: 1,
      x: 310,
      y: 518,
      width: 155,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_a',
      sectionTitle: 'A. General Information',
    },
    {
      key: 'client_dob',
      label: 'Date of Birth',
      type: 'date',
      readonly: true,
      page: 1,
      x: 475,
      y: 513,
      width: 110,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_a',
      sectionTitle: 'A. General Information',
    },
    {
      key: 'company_name',
      label: 'Company Name',
      type: 'text',
      page: 1,
      x: 45,
      y: 480,
      width: 250,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_a',
      sectionTitle: 'A. General Information',
      placeholder: 'Sun Life of Canada (Philippines), Inc.',
    },
    {
      key: 'designation',
      label: 'Designation',
      type: 'text',
      page: 1,
      x: 310,
      y: 480,
      width: 250,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_a',
      sectionTitle: 'A. General Information',
      placeholder: 'e.g. Authorized Signatory / Owner',
    },

    // B1: Specific Policy
    {
      key: 'request_type_specific',
      label: 'B.1 Specific Policy / Plan / Account Number(s)',
      type: 'radio',
      page: 1,
      x: 51,
      y: 435,
      width: 16,
      height: 16,
      radioValue: 'specific_policy',
      sectionKey: 'section_b',
      sectionTitle: 'B. Request Details',
      description: 'Transfer specific policy/plan/account numbers.',
    },
    {
      key: 'policy_numbers',
      label: 'Policy / Plan / Account Number(s)',
      type: 'textarea',
      page: 1,
      x: 55,
      y: 395,
      width: 500,
      height: 35,
      fontSize: 8.5,
      dependsOn: { key: 'request_type', value: 'specific_policy' },
      sectionKey: 'section_b',
      sectionTitle: 'B. Request Details',
      placeholder: 'Enter policy / account numbers separated by commas or lines',
    },

    // B2: All Accounts
    {
      key: 'request_type_all',
      label: 'B.2 ALL Existing Client Accounts',
      type: 'radio',
      page: 1,
      x: 51,
      y: 350,
      width: 16,
      height: 16,
      radioValue: 'all_accounts',
      sectionKey: 'section_b',
      sectionTitle: 'B. Request Details',
      description: 'Transfer all accounts of selected categories as of request date.',
    },
    {
      key: 'account_individual_life',
      label: 'All Individual Life Insurance Policies',
      type: 'checkbox',
      page: 1,
      x: 51,
      y: 279.8,
      width: 14,
      height: 14,
      dependsOn: { key: 'request_type', value: 'all_accounts' },
      sectionKey: 'section_b',
      sectionTitle: 'B. Request Details',
    },
    {
      key: 'account_group_life',
      label: 'All Group Life Insurance Contracts',
      type: 'checkbox',
      page: 1,
      x: 51,
      y: 267.8,
      width: 14,
      height: 14,
      dependsOn: { key: 'request_type', value: 'all_accounts' },
      sectionKey: 'section_b',
      sectionTitle: 'B. Request Details',
    },
    {
      key: 'account_mutual_fund',
      label: 'All Mutual Fund Accounts',
      type: 'checkbox',
      page: 1,
      x: 51,
      y: 255.8,
      width: 14,
      height: 14,
      dependsOn: { key: 'request_type', value: 'all_accounts' },
      sectionKey: 'section_b',
      sectionTitle: 'B. Request Details',
    },
    {
      key: 'account_pre_need',
      label: 'All Pre-Need Plans',
      type: 'checkbox',
      page: 1,
      x: 51,
      y: 243.8,
      width: 14,
      height: 14,
      dependsOn: { key: 'request_type', value: 'all_accounts' },
      sectionKey: 'section_b',
      sectionTitle: 'B. Request Details',
    },
    {
      key: 'reference_policy_number',
      label: 'Reference Policy Number',
      type: 'text',
      page: 1,
      x: 330,
      y: 233,
      width: 200,
      height: 18,
      fontSize: 8.5,
      dependsOn: { key: 'request_type', value: 'all_accounts' },
      sectionKey: 'section_b',
      sectionTitle: 'B. Request Details',
      placeholder: 'Specify at least 1 policy/account number for reference',
    },

    // C: Reason for Change
    {
      key: 'reason_type_no_advisor',
      label: 'Current policy has no designated advisor',
      type: 'radio',
      page: 1,
      x: 51,
      y: 188.9,
      width: 14,
      height: 14,
      radioValue: 'no_advisor',
      sectionKey: 'section_c',
      sectionTitle: 'C. Reason for Change',
    },
    {
      key: 'reason_type_prefer_another',
      label: 'I prefer to be serviced by another advisor',
      type: 'radio',
      page: 1,
      x: 51,
      y: 176.9,
      width: 14,
      height: 14,
      radioValue: 'prefer_another',
      sectionKey: 'section_c',
      sectionTitle: 'C. Reason for Change',
    },
    {
      key: 'reason_details',
      label: 'Reason Details / Explanation',
      type: 'textarea',
      page: 1,
      x: 55,
      y: 158,
      width: 500,
      height: 35,
      fontSize: 8.5,
      dependsOn: { key: 'reason_type', value: 'prefer_another' },
      sectionKey: 'section_c',
      sectionTitle: 'C. Reason for Change',
      placeholder: 'Provide justification for changing advisor',
    },

    // ════════════════════════════════════════════════════════════════════════
    // PAGE 2
    // ════════════════════════════════════════════════════════════════════════
    {
      key: 'new_advisor_last_name',
      label: 'New Advisor Last Name',
      type: 'text',
      page: 2,
      x: 35,
      y: 707,
      width: 175,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_d',
      sectionTitle: 'D. New Advisor Information',
      required: true,
      placeholder: 'Last Name',
    },
    {
      key: 'new_advisor_first_name',
      label: 'New Advisor First Name',
      type: 'text',
      page: 2,
      x: 218,
      y: 707,
      width: 175,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_d',
      sectionTitle: 'D. New Advisor Information',
      required: true,
      placeholder: 'First Name',
    },
    {
      key: 'new_advisor_middle_name',
      label: 'New Advisor Middle Name',
      type: 'text',
      page: 2,
      x: 401,
      y: 707,
      width: 175,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_d',
      sectionTitle: 'D. New Advisor Information',
      placeholder: 'Middle Name',
    },

    // E: Acknowledgments & Signatures
    {
      key: 'client_full_name_pg2',
      label: 'Complete Name of Policy Owner',
      type: 'readonly',
      page: 2,
      x: 35,
      y: 467,
      width: 540,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_e',
      sectionTitle: 'E. Signatures & Acknowledgments',
    },
    {
      key: 'place_of_signing',
      label: 'Place of Signing',
      type: 'text',
      page: 2,
      x: 35,
      y: 434,
      width: 380,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_e',
      sectionTitle: 'E. Signatures & Acknowledgments',
      placeholder: 'City / Municipality',
    },
    {
      key: 'date_of_signing',
      label: 'Date of Signing',
      type: 'date',
      page: 2,
      x: 457,
      y: 441,
      width: 120,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_e',
      sectionTitle: 'E. Signatures & Acknowledgments',
    },
    {
      key: 'policy_owner_signature',
      label: 'Policy Owner / Planholder Signature',
      type: 'signature',
      page: 2,
      x: 35,
      y: 358,
      width: 540,
      height: 40,
      sectionKey: 'section_e',
      sectionTitle: 'E. Signatures & Acknowledgments',
      required: true,
    },
    {
      key: 'new_advisor_signature',
      label: 'New Advisor Signature',
      type: 'signature',
      page: 2,
      x: 35,
      y: 330,
      width: 175,
      height: 35,
      sectionKey: 'section_e',
      sectionTitle: 'E. Signatures & Acknowledgments',
    },
    {
      key: 'code_number',
      label: 'Advisor Code Number',
      type: 'text',
      page: 2,
      x: 218,
      y: 355,
      width: 175,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_e',
      sectionTitle: 'E. Signatures & Acknowledgments',
      placeholder: 'Code #',
    },
    {
      key: 'nbo_iso',
      label: 'NBO / ISO',
      type: 'text',
      page: 2,
      x: 401,
      y: 355,
      width: 175,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_e',
      sectionTitle: 'E. Signatures & Acknowledgments',
      placeholder: 'NBO / ISO',
    },

    // F: Communication Preference
    {
      key: 'wants_communication_yes',
      label: 'Yes - I want to receive communication',
      type: 'radio',
      page: 2,
      x: 130,
      y: 167,
      width: 14,
      height: 14,
      radioValue: true,
      sectionKey: 'section_f',
      sectionTitle: 'F. Communication Preference',
    },
    {
      key: 'wants_communication_no',
      label: 'No - I do not want to receive communication',
      type: 'radio',
      page: 2,
      x: 162,
      y: 167,
      width: 14,
      height: 14,
      radioValue: false,
      sectionKey: 'section_f',
      sectionTitle: 'F. Communication Preference',
    },

    // G: For Office Use Only
    {
      key: 'received_by_staff',
      label: 'Received By (Staff Name)',
      type: 'text',
      page: 2,
      x: 55,
      y: 102,
      width: 250,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_g',
      sectionTitle: 'G. For Office Use Only',
      placeholder: 'Staff Name',
    },
    {
      key: 'receiving_department',
      label: 'Receiving Department / Office',
      type: 'text',
      page: 2,
      x: 320,
      y: 102,
      width: 250,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_g',
      sectionTitle: 'G. For Office Use Only',
      placeholder: 'Branch / Dept',
    },
    {
      key: 'date_received',
      label: 'Date Received',
      type: 'date',
      page: 2,
      x: 158,
      y: 74,
      width: 150,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_g',
      sectionTitle: 'G. For Office Use Only',
    },
    {
      key: 'time_received',
      label: 'Time Received',
      type: 'text',
      page: 2,
      x: 327,
      y: 62,
      width: 150,
      height: 18,
      fontSize: 8.5,
      sectionKey: 'section_g',
      sectionTitle: 'G. For Office Use Only',
      placeholder: 'e.g. 02:30 PM',
    },
  ],
};
